apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-client
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongo-client
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - name: mongo-client
        image: mongo:4.4.0
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          # requests:
          #   memory: "512Mi"
          #   cpu: "500m"
          limits:
            memory: "100Mi"
            cpu: "100m"