apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: ops-manager
  namespace: mongodb
spec:
  replicas: 1
  version: 5.0.2
  adminCredentials: admin-secret
  configuration:
    # passing mms.ignoreInitialUiSetup=true allows to avoid the setup wizard in Ops Manager. Note, that
    # this requires to set some mandatory configuration properties, see
    # https://docs.opsmanager.mongodb.com/current/reference/configuration/index.html#mms.ignoreInitialUiSetup
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: mongodb
    mms.adminEmailAddr: support@example.com
    mms.fromEmailAddr: support@example.com
    mms.replyToEmailAddr: support@example.com
    mms.mail.hostname: email-smtp.us-east-1.amazonaws.com
    mms.mail.port: "465"
    mms.mail.ssl: "true"
    mms.mail.transport: smtp
    mms.minimumTLSVersion: TLSv1.2
  externalConnectivity:
    type: NodePort
    port: 30036
  backup:
    enabled: false
  statefulSet:
    spec:
      template:
        spec:
          securityContext:
            fsGroup: 5000
            runAsUser: 5000
          containers:
            - name: mongodb-ops-manager
              resources:
                limits:
                  cpu: '2'
                  memory: 4G
  applicationDatabase:
    members: 3
    version: 4.4.4-ent
    podSpec:
      cpu: '0.5'
      memory: 500M
      persistence:
        single:
          storage: 16G
          storageClass: local-path