---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsmanager-db0
spec:
  storageClassName: ""
  capacity:
    storage: 16Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
     namespace: mongodb
     name: data-ops-manager-db-0
  hostPath:
    path: "/root/pv/mongodb/opsmanager/db0"
    type: "DirectoryOrCreate"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsmanager-db1
spec:
  storageClassName: ""
  capacity:
    storage: 16Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
     namespace: mongodb
     name: data-ops-manager-db-1
  hostPath:
    path: "/root/pv/mongodb/opsmanager/db1"
    type: "DirectoryOrCreate"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: opsmanager-db2
spec:
  storageClassName: ""
  capacity:
    storage: 16Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
     namespace: mongodb
     name: data-ops-manager-db-2
  hostPath:
    path: "/root/pv/mongodb/opsmanager/db2"
    type: "DirectoryOrCreate"

---