# Ops-Manager Organization and Project
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-shard
  namespace: mongodb
data:
  projectName: project-shard
  orgId: 61a7241df7c8cf61a88825f8 # Optional
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080

---

# Ops-Manager Organization and Project
apiVersion: v1
kind: ConfigMap
metadata:
  name: project-replicaset
  namespace: mongodb
data:
  projectName: project-replicaset
  orgId: 61a7241df7c8cf61a88825f8 # Optional
  baseUrl: http://ops-manager-svc.mongodb.svc.cluster.local:8080

---
# Ops-Manager API Key for Organization
apiVersion: v1
kind: Secret
metadata:
  name: ops-manager-apikey
  namespace: mongodb
type: Opaque
stringData:
  publicKey: abefnjzg
  privateKey: 034f593f-e5a9-4138-84b5-a31b47651229