apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: shard
  namespace: mongodb
spec:
  shardCount: 1
  mongodsPerShardCount: 3
  mongosCount: 2
  configServerCount: 1
  version: 4.4.0-ent
  type: ShardedCluster
  opsManager:
    configMapRef:
      name: project-shard
  credentials: ops-manager-apikey
  persistent: false
  exposedExternally: true
  security:
    authentication:
      enabled: true
      modes: ["SCRAM"] # Valid authentication modes are "SCRAM' and "X509"
      ignoreUnknownUsers: true # default value false
  configSrvPodSpec:
    podTemplate:
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "2"
                memory: 2G
    # persistence:
    #   single:
    #     storage: 16G
    #     storageClass: local-path
  mongosPodSpec:
    podTemplate:
      metadata:
          labels:
            monitoring: "true"
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "4"
                memory: 4G
          - name: prom-exporter
            image: percona/mongodb_exporter:0.20
            imagePullPolicy: Always
            args: ["--compatible-mode", "--mongodb.uri", "mongodb://prom-exporter:P%40ssw0rd@127.0.0.1:27017/admin?ssl=false"]
            ports:
              - name: metrics
                containerPort: 9216
                protocol: TCP
            resources:
              limits:
                cpu: "0.1"
                memory: 100M
  shardPodSpec:
    podTemplate:
      metadata:
        labels:
          monitoring: "true"
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "0.5"
                memory: 500M
          - name: prom-exporter
            image: percona/mongodb_exporter:0.20
            imagePullPolicy: Always
            args: ["--compatible-mode", "--mongodb.uri", "mongodb://prom-exporter:P%40ssw0rd@127.0.0.1:27017/admin?ssl=false"]
            ports:
              - name: metrics
                containerPort: 9216
                protocol: TCP
            resources:
              limits:
                cpu: "0.1"
                memory: 100M
          # - name: prom-exporter
          #   image: ssheehy/mongodb-exporter:0.11.0
          #   imagePullPolicy: Always
          #   resources:
          #     limits:
          #       cpu: "0.1"
          #       memory: "100M"
          #   ports:
          #     - name: metrics
          #       containerPort: 9216
          #       protocol: TCP
          #   env:
          #   - name: MONGODB_URI
          #     value: "mongodb://prom-exporter:P%40ssw0rd@127.0.0.1:27017/admin?ssl=false"
    # persistence:
    #   single:
    #     storage: 16G
    #     storageClass: local-path
